/* eslint-disable @next/next/no-page-custom-font */
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Providers from "@/components/ProgressBarProvider";
const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "PT. Sumber Berkat Komputindo ",
	description: "Generated by create next app",
	icons: {
		icon: "/logo-dark.png",
	},
};

export default function RootLayout({ children }) {
	return (
		<html
			lang="en"
			data-darkreader-scheme="white"
			data-darkreader-mode="dynamic"
		>
			<head>
				{/* Google Fonts */}
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
					crossOrigin="true"
				/>
				<link
					href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&family=Outfit:wght@100..900&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
					rel="stylesheet"
				/>
				<link rel="icon" href="/logo-dark.png" type="image/png" sizes="any" />
				<title>Sumber berkat Komputindo</title>
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased `}
			>
				<Navbar />
				<Providers>{children}</Providers>

				<Footer />
			</body>
		</html>
	);
}
